ALTER SEQUENCE projects_id_seq INCREMENT BY 50;
ALTER SEQUENCE ticket_comments_id_seq INCREMENT BY 50;
ALTER SEQUENCE ticket_log_id_seq INCREMENT BY 50;
ALTER SEQUENCE tickets_id_seq INCREMENT BY 50;
ALTER SEQUENCE users_id_seq INCREMENT BY 50;
